export const REQUEST_TOKEN = 'REQUEST_TOKEN';
export const GET_TOKEN = 'GET_TOKEN';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SUBMIT_QUESTIONS = 'SUBMIT_QUESTIONS';
export const GET_QUESTIONS = 'GET_QUESTIONS';
